export const funFacts = [
    "The first Model UN conference was held at Harvard University in 1955, simulating the League of Nations.",
    "Model UN conferences are held in over 100 countries, with the largest conferences hosting over 5,000 delegates.",
    "The United Nations was founded in 1945 after World War II to prevent future conflicts.",
    "There are 193 member states in the United Nations.",
    "Vatican City and Palestine are non-member observer states at the UN.",
    "The UN Headquarters is located in New York City, on international territory.",
    "The six official languages of the UN are Arabic, Chinese, English, French, Russian, and Spanish.",
    "The Security Council has 15 members: 5 permanent (with veto power) and 10 non-permanent.",
    "The 5 permanent members of the UNSC are China, France, Russia, the UK, and the USA.",
    "The Universal Declaration of Human Rights was adopted in 1948.",
    "Ban Ki-moon served as the 8th Secretary-General of the UN from 2007 to 2016.",
    "António Guterres is the current Secretary-General of the United Nations.",
    "The International Court of Justice (ICJ) is the principal judicial organ of the UN, located in The Hague.",
    "UN Peacekeepers are often referred to as 'Blue Helmets'.",
    "UNICEF operates in over 190 countries and territories to save children's lives.",
    "WHO (World Health Organization) is a specialized agency responsible for international public health.",
    "UNESCO stands for United Nations Educational, Scientific and Cultural Organization.",
    "The Sustainable Development Goals (SDGs) are a collection of 17 interlinked global goals designed to be a 'blueprint to achieve a better and more sustainable future for all'.",
    "ECOSOC stands for the Economic and Social Council, one of the six principal organs of the UN.",
    "The General Assembly is the main deliberative, policymaking, and representative organ of the UN.",
    "A 'Point of Personal Privilege' is the only point that can interrupt a speaker.",
    "In MUN, 'Motion to Suspend the Meeting' is used to go into an unmoderated caucus.",
    "A 'Point of Parliamentary Inquiry' is used to ask the chair a question about the rules of procedure.",
    "A 'Moderated Caucus' is a debate format where delegates speak for a set time on a specific sub-issue.",
    "An 'Unmoderated Caucus' allows delegates to leave their seats and discuss freely.",
    "A 'Sponsor' is a delegate who helps write a resolution.",
    "A 'Signatory' is a delegate who wants to see a resolution debated, but may not agree with all of it.",
    "The 'Dais' is the raised platform where the chair and other officials sit.",
    "A 'Gavel' is the mallet used by the chair to maintain order.",
    "To 'Yield to the Chair' means to give up the remaining time to the moderator.",
    "To 'Yield to Another Delegate' means to give the remaining time to another speaker.",
    "To 'Yield to Questions' means to use the remaining time to answer questions from other delegates.",
    "A 'Role Call' is used to determine if a quorum is present.",
    "A 'Quorum' is the minimum number of members that must be present to validly conduct business.",
    "A 'Veto' is the power to unilaterally stop an official action, held by the P5 in the UNSC.",
    "The 'Speakers List' determines the order in which delegates will speak.",
    "A 'Draft Resolution' is a document written by delegates detailing solutions to the topic.",
    "An 'Amendment' is a change or addition to a draft resolution.",
    "A 'Flow of Debate' refers to the order in which events happen during a committee session.",
    "Decorum' is the order and respect required during a committee session.",
    "A 'Position Paper' is a document outlining a country's policy on the topics.",
    "The 'Secretary-General' is the chief administrative officer of the UN.",
    "The 'Secretariat' carries out the day-to-day work of the UN under the Secretary-General.",
    "The 'Trusteeship Council' suspended operation in 1994 after Palau attained independence.",
    "The 'Charter of the United Nations' is the foundational treaty of the UN.",
    "The 'League of Nations' was the predecessor to the United Nations.",
    "There are 54 members in ECOSOC.",
    "The UN budget is funded by assessed and voluntary contributions from member states.",
    "The UN flag features a map of the world centered on the North Pole, surrounded by olive branches.",
    "Olive branches symbolize peace.",
    "The term 'United Nations' was coined by Franklin D. Roosevelt.",
    "The UN was officially established on October 24, 1945.",
];
